### ISSUE TITLE
SmartHealthCardJwsDecoder.DecodePayloadAsync(..., Verify: false) does not disable required SmartHealthCardModel json property checks

### ISSUE THREAD

**Issue by NickDrouin** [angusmillar/SmartHealthCard#10]
#### Motivation
Quebec, Canada, uses QR-code-based vaccine passports.  These generally follow the SMART Health Card Framework, but are non-compliant in that they lack the "nbf" property.  I would still like to use the library, but despite requesting no verification, it still throws an error.

#### Code flow
Here in the [SmartHealthCardJwsDecoder](https://github.com/angusmillar/SmartHealthCard/blob/master/SmartHealthCard.Token/JwsToken/SmartHealthCardJwsDecoder.cs#L63-L65) the payload is unzipped and parsed.  However, the code does not pass on the Verify flag, and the Newtonsoft.Json.JsonSerializer within [SmartHealthCard.Token.Serializers.Json.JsonSerializer](https://github.com/angusmillar/SmartHealthCard/blob/master/SmartHealthCard.Token/Serializers/Json/JsonSerializer.cs) remains strict and throws when the nbf property defined in SmartHealthCardModel is missing.

#### Work-around
I set [JsonProperty nfb](https://github.com/angusmillar/SmartHealthCard/blob/master/SmartHealthCard.Token/Model/Shc/SmartHealthCardModel.cs#L30) to .Default.

#### Avenues for a fix
Consider propagating Verify down to the serializer constructor/configuration of your JsonSerializer.  For example, the implementation of a handler for Serializer_Error allows the implementer to set Newtonsoft.Json.Serialization.ErrorEventArgs.ErrorContext.Handled = true when Verify is false.

Alternatively, use .Default for all models and explicitly verify as needed, when the flag is set.

> Nit: Verify is written as Verity in a few places in the code.

Thanks for the lib, great work!

**Comment by angusmillar** [comment]
Hi @NickDrouin, sorry been a bit flat out of late. II will try and look into this over the weekend.

**Comment by angusmillar** [comment]
Hi @NickDrouin , I have just published an updated  V1.0.4  SmartHealthCard.Token NuGet package that addresses your issue.

I relaxed the requirement that Smart Health Card tokens must have a IssuanceDate (nbf) property when being decoded. If not found the library defaults the IssuanceDate property to the UNIX epoch start time of 00:00:00 UTC on 1 January 1970.
You should now be able to decode the tokens you spoke of, with or without the Verify turned on. 
If Verify is True it will validate the defaulted 'nbf' date of 00:00:00 UTC on 1 January 1970, which should not be an issue.

I went with the option of setting the JSON parser to .Default and I was already explicitly verifying the 'nbf' date. With the JSON parse set to default it defaults the IssuanceDate (which is of datatype double) to zero which is  00:00:00 UTC on 1 January 1970. The downside here is your SmartHealthCardModel that is returned by the library for your JWS that has no 'nbf', will have a non-null IssuanceDate of '0' even though your physical token has no 'nbf' property. But I can't see that being a problem. 

Hope this helps you out.

PS: I forgot to correct the spelling mistake on Verity -> Verify. I will get around to it later. I'm a terrible speller.
