### ISSUE TITLE
Need Support For Processing EU Digital Vaccine Card 

### ISSUE THREAD

**Issue by hiteshmehramca** [angusmillar/SmartHealthCard#11]
Hi @angusmillar

The library has been a big help for us to process SmartHealthCard and we wanted to see if we can use it for EU Vaccine Card.

While accessing the QR code for EU vaccine card we are getting HC1 details instead of SHC details 

We are able to use your library to retrieve Immunization Info from SHC1 where QR payload is of form:
SHC:/56762909524320603460292437404460<snipped for brevity>

We are trying to evaluate how we can use your library for HC1:
HC1:6BFW70F90T9WJWG.FKY*4GO0RKPNHILCJ$VBFBB4W0*<snipped for brevity>

We found below links while researching for implementation of EU Digital Vaccine Card 
1. QR Code (Extract to get HC1 details)
2. Extracted HC1 Data From QR Code (.txt File)
3. https://dencode.com/en/string/base45 (To get vaccine info from HC1)
4. https://www.nuget.org/packages/DigitalCovidCertificate (Existing library to extract vaccine information from HC1)

![QRCode-1](https://user-images.githubusercontent.com/83389340/139659994-cd2b0352-87f5-47e1-a552-0d589b737335.png)
[HC1 Sample Data.txt](https://github.com/angusmillar/SmartHealthCard/files/7452510/HC1.Sample.Data.txt)
![QRCode-2](https://user-images.githubusercontent.com/83389340/139660018-a7fa7170-c5ce-45eb-ba38-a36fefc52f8e.png)

**Comment by angusmillar** [comment]
Hi @hiteshmehramca, while it is a tempting request it would be a significant bit of work. Unfortunatly I don't have the spare time to focus on it in the near term.  This may change if I find I need to create EU Green cards myself, yet that pressure has not been applied as yet. Up to my ears in Covid IATA Travel Pass work, amung other projects.
Sorry I coudln't help here.
