### ISSUE TITLE
COVID 19 Vaccination Apple Wallet

### ISSUE THREAD

**Issue by aravindh-j** [angusmillar/SmartHealthCard#12]
Hi

I want to create an Apple wallet for COVID 19 Vaccination Pass (https://support.apple.com/en-us/HT212752). As of now, I have generated the QR Code with the help of this NuGet package but after I scanned that QR code on my iPhone it's open the Health App with the COVID-related Data. But, I want to add the Same data to both Health App and Apple Wallet like the above-mentioned URL.

**FhirBundleJson**
{"resourceType":"Bundle","type":"collection","entry":[{"fullUrl":"resource:0","resource":{"resourceType":"Patient","name":[{"family":"Anyperson","given":["John","B."]}],"birthDate":"1951-01-20"}},{"fullUrl":"resource:1","resource":{"resourceType":"Immunization","status":"completed","vaccineCode":{"coding":[{"system":"http://hl7.org/fhir/sid/cvx","code":"207"}]},"patient":{"reference":"resource:0"},"occurrenceDateTime":"2021-01-01","performer":[{"actor":{"display":"ABCGeneralHospital"}}],"lotNumber":"0000001"}},{"fullUrl":"resource:2","resource":{"resourceType":"Immunization","status":"completed","vaccineCode":{"coding":[{"system":"http://hl7.org/fhir/sid/cvx","code":"207"}]},"patient":{"reference":"resource:0"},"occurrenceDateTime":"2021-01-29","performer":[{"actor":{"display":"ABCGeneralHospital"}}],"lotNumber":"0000007"}}]}

So, Can you please help guide me to resolve these issues?

**Comment by angusmillar** [comment]
Closing this issue as its a request for Apple support, not an issue with this library's Smart Health Card implementation.
