### ISSUE TITLE
Result for Static Method Result<T>.Retry(...) Does Not Set Retryable to True

### ISSUE THREAD

**Issue by DandiAndy** [angusmillar/SmartHealthCard#6]
Hi @angusmillar,

Thanks for all your hard work on this. Your project is really helping my team ramp up quickly with our application.

I noticed that in your Result support class that Retryable does get set correctly for the constructor. See line 139:

https://github.com/angusmillar/SmartHealthCard/blob/a600df729d3408694258ff6ded81246faaab38b4/SmartHealthCard.Token/Support/Result.cs#L138-L142

Retryable is set False, when it should really be set to the incoming parameter.

Thanks!

**Comment by angusmillar** [comment]
HI @DandiAndy, Thanks for pointing this out.  I have fixed the constructor issue you pointed out. This bug had no effect on the library as it was. The retry functionality was not used anywhere at this time.
However, in response to fixing it, I have now implement retry logic for the HTTP request to get the JWKS (Public Key) when validating token signatures.  So moving forward the Retry is now in use.
Thank you for submitting the issue and improving the library. 
PS: There is a new Nuget package SmartHealthCard.Token  V1.0.2 which has this Retry working. It also has a critical bug fix which I strongly advise your upgrade to. The bug prevented invalid token signatures from being reported as invalid. Not a very nice bug to have!

**Comment by DandiAndy** [comment]
Thanks @angusmillar!
